# Generated by Django 3.2.3 on 2021-06-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('credential', models.CharField(max_length=255)),
                ('specialty', models.CharField(choices=[('oncology', 'Oncology'), ('second', 'Second'), ('third', 'Third')], max_length=255)),
            ],
        ),
    ]
